/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controladora.Main;
import UML.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class VCalendario extends javax.swing.JDialog {

    /**
     * Creates new form VCalendario
     */
    private ArrayList<Jornada> jornadas;
    private int pos=0;
    public VCalendario() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        obtenerDatos();
        rellenar(pos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Njornada = new javax.swing.JLabel();
        lbFechaIni = new javax.swing.JLabel();
        lbFechaFin = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        spPartidos = new javax.swing.JScrollPane();
        bPrimero = new javax.swing.JButton();
        bAnterior = new javax.swing.JButton();
        bSiguiente = new javax.swing.JButton();
        bUltimo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Jornada");

        Njornada.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Njornada.setText("X");

        lbFechaIni.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbFechaIni.setText("FechaIni");

        lbFechaFin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbFechaFin.setText("FechaFin");

        Label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Label2.setText("-");

        spPartidos.setBorder(null);

        bPrimero.setText("|<");
        bPrimero.setEnabled(false);
        bPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrimeroActionPerformed(evt);
            }
        });

        bAnterior.setText("<");
        bAnterior.setEnabled(false);
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });

        bSiguiente.setText(">");
        bSiguiente.setEnabled(false);
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });

        bUltimo.setText(">|");
        bUltimo.setEnabled(false);
        bUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(lbFechaIni)
                        .addGap(28, 28, 28)
                        .addComponent(Label2)
                        .addGap(27, 27, 27)
                        .addComponent(lbFechaFin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Njornada))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(spPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(bPrimero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAnterior)
                        .addGap(94, 94, 94)
                        .addComponent(bSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bUltimo)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Njornada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFechaIni)
                    .addComponent(lbFechaFin)
                    .addComponent(Label2))
                .addGap(50, 50, 50)
                .addComponent(spPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPrimero)
                    .addComponent(bAnterior)
                    .addComponent(bUltimo)
                    .addComponent(bSiguiente))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrimeroActionPerformed
        pos = 0;
        rellenar(pos);
        bSiguiente.setEnabled(true);
        bUltimo.setEnabled(true);
        bPrimero.setEnabled(false);
        bAnterior.setEnabled(false);

    }//GEN-LAST:event_bPrimeroActionPerformed

    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
        pos--;
        rellenar(pos);
        bSiguiente.setEnabled(true);
        bUltimo.setEnabled(true);
        if(pos == 0){
            bPrimero.setEnabled(false);
            bAnterior.setEnabled(false);
        }

    }//GEN-LAST:event_bAnteriorActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        pos++;
        rellenar(pos);
        bPrimero.setEnabled(true);
        bAnterior.setEnabled(true);
        if(pos == jornadas.size()-1){
            bSiguiente.setEnabled(false);
            bUltimo.setEnabled(false);
        }
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void bUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUltimoActionPerformed
        pos = jornadas.size()-1;
        rellenar(pos);
        bSiguiente.setEnabled(false);
        bUltimo.setEnabled(false);
        bPrimero.setEnabled(true);
        bAnterior.setEnabled(true);
    }//GEN-LAST:event_bUltimoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Njornada;
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bPrimero;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JButton bUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbFechaFin;
    private javax.swing.JLabel lbFechaIni;
    private javax.swing.JScrollPane spPartidos;
    // End of variables declaration//GEN-END:variables

    private void obtenerDatos() {
        try {
        jornadas= Main.consultarTodasLasJornadas();
        } catch (Exception ex) {
            Logger.getLogger(VCalendario.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int x=0;x<jornadas.size();x++){
            try {
                jornadas.get(x).setListaPartidos(Main.BuscarPartidosPorJornada(jornadas.get(x).getIdJornada()));
            } catch (Exception ex) {
                Logger.getLogger(VCalendario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(jornadas.size()>1){
            bSiguiente.setEnabled(true);
            bUltimo.setEnabled(true);
        }
    }

    private void rellenar(int pos) {
        Njornada.setText(String.valueOf(jornadas.get(pos).getIdJornada()));
        lbFechaIni.setText(String.valueOf(jornadas.get(pos).getFechaInicio()));
        lbFechaFin.setText(String.valueOf(jornadas.get(pos).getFechaFinal()));
        String titulos[] ={"Equipos","Fecha","Lugar"};
        String datos [] []= new String[jornadas.get(pos).getListaPartidos().size()] [3];
        for (int x=0; x < datos.length;x++){
            datos [x][0] = jornadas.get(pos).getListaPartidos().get(x).geteLocal().getNombre()+"  VS  "+jornadas.get(pos).getListaPartidos().get(x).geteVisitante().getNombre();
            datos [x][1] = String.valueOf(jornadas.get(pos).getListaPartidos().get(x).getFecha());
            datos [x][2] = jornadas.get(pos).getListaPartidos().get(x).geteLocal().getLugar();
        }
        JTable tPartidos = new JTable (datos,titulos);
        tPartidos.setEnabled(false);
        tPartidos.setShowGrid(false);
        spPartidos.setViewportView(tPartidos);
        
        
    }
}
