/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controladora.Main;
import Excepciones.Excepcion;
import java.awt.Color;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 * Vista para la carga del login.
 * Fecha de creación de la vista: 23/04/2018
 * @author eqdaw04
 */
public class VLogin extends javax.swing.JFrame {

    int error, cont = 0;
    
    public VLogin() {
        initComponents();
        CrearImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        bAcceder = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        pfContrasenna = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        imgusu = new javax.swing.JLabel();
        imgpassw = new javax.swing.JLabel();
        logotipo = new javax.swing.JLabel();
        imgfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 66, 255));
        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(562, 496));
        setMinimumSize(new java.awt.Dimension(562, 496));
        setPreferredSize(new java.awt.Dimension(562, 496));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel1.setText("¡Bienvenidos a E-Sport!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 40, 450, 70);

        tfUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfUsuario.setText("admin");
        tfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(tfUsuario);
        tfUsuario.setBounds(190, 150, 150, 30);

        bAcceder.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        bAcceder.setText("Acceder");
        bAcceder.setAutoscrolls(true);
        bAcceder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bAcceder.setPreferredSize(new java.awt.Dimension(67, 31));
        bAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAccederActionPerformed(evt);
            }
        });
        getContentPane().add(bAcceder);
        bAcceder.setBounds(110, 300, 120, 40);

        bSalir.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        bSalir.setText("Salir");
        bSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bSalir);
        bSalir.setBounds(290, 300, 120, 40);

        pfContrasenna.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pfContrasenna.setText("root");
        getContentPane().add(pfContrasenna);
        pfContrasenna.setBounds(190, 230, 150, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 410, 69, 22);

        jLabel4.setText("1. Clase; 2. Jon; 3. Mikel");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 380, 160, 16);
        getContentPane().add(imgusu);
        imgusu.setBounds(130, 150, 40, 40);
        getContentPane().add(imgpassw);
        imgpassw.setBounds(130, 220, 40, 40);

        logotipo.setAlignmentX(0.5F);
        getContentPane().add(logotipo);
        logotipo.setBounds(480, 390, 80, 70);
        getContentPane().add(imgfondo);
        imgfondo.setBounds(0, 0, 560, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para obtener la contraseña.
     * @return devuelve la contraseña 
     */
    
    private  void CrearImagenes(){
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(70, 130, 180));
        
        setTitle("Bienvenido a E-Sport");
        
        ImageIcon usuario = new ImageIcon("../../imagenes/user.png");
        Icon icono = new ImageIcon (usuario.getImage().getScaledInstance(imgusu.getWidth(), imgusu.getHeight(), Image.SCALE_DEFAULT));
        imgusu.setIcon(icono);
        this.repaint();
        
        ImageIcon passw = new ImageIcon("../../imagenes/contrasenna.png");
        Icon icono2 = new ImageIcon (passw.getImage().getScaledInstance(imgpassw.getWidth(), imgpassw.getHeight(), Image.SCALE_DEFAULT));
        imgpassw.setIcon(icono2);
        this.repaint();
        
        ImageIcon logo = new ImageIcon("../../imagenes/4fan.png");
        Icon icono3 = new ImageIcon(logo.getImage().getScaledInstance(logotipo.getWidth(), logotipo.getHeight(), Image.SCALE_DEFAULT));
        logotipo.setIcon(icono3);
        this.repaint();
        
        ImageIcon fondo = new ImageIcon("../../imagenes/fondo2.jpg");
        Icon icono4 = new ImageIcon (fondo.getImage().getScaledInstance(imgfondo.getWidth(), imgfondo.getHeight(), Image.SCALE_DEFAULT));
        imgfondo.setIcon(icono4);
        this.repaint();
        
        try {
            Thread.sleep(5000);
        } catch (InterruptedException ex) {
            Logger.getLogger(VLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextField1.grabFocus();
        setVisible(true);
    }
    
    public JPasswordField getPfContrasenna() {
        return pfContrasenna;
    }
    
    /**
     * Metodo para obtener el usuario.
     * @return devuelve el usuario
     */

    public JTextField getTfUsuario() {
        return tfUsuario;
    }
    
    /**
     * Metodo para obtener errores.
     * @return devuelve un error
     */

    public int getError() {
        return error;
    }

    public void setError(int error) {
        this.error = error;
    }

    public int getCont() {
        return cont;
    }

    public void setCont(int cont) {
        this.cont = cont;
    }
    
    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        Main.salir(this);
    }//GEN-LAST:event_bSalirActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        try
        {
            if (tfUsuario.getText().isEmpty())
            {
                throw new Excepcion(1);
            }
            else if (String.copyValueOf(pfContrasenna.getPassword()).isEmpty())
            {
                throw new Excepcion(2);
            }
            else{
                
                Main.accederPrincipal(tfUsuario.getText(), pfContrasenna.getPassword(), Integer.parseInt(jTextField1.getText()) );
            }
        }
        catch (Excepcion e)
        {
            pfContrasenna.setText("");
            pfContrasenna.grabFocus();
            JOptionPane.showMessageDialog(this, e.getMessage() + "(" + cont + "/3)", "Error", 0);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getClass() + " \n " + e.getMessage(), "Error", 0);
        }
        finally{
            if(error == 13){
                Main.salir(this);
            }
        }
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try
        {
            if (tfUsuario.getText().isEmpty())
            {
                throw new Excepcion(1);
            }
            else if (String.copyValueOf(pfContrasenna.getPassword()).isEmpty())
            {
                throw new Excepcion(2);
            }
            else{
                
                Main.accederPrincipal(tfUsuario.getText(), pfContrasenna.getPassword(), Integer.parseInt(jTextField1.getText()) );
            }
        }
        catch (Excepcion e)
        {
            pfContrasenna.setText("");
            pfContrasenna.grabFocus();
            JOptionPane.showMessageDialog(this, e.getMessage() + "(" + cont + "/3)", "Error", 0);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getClass() + " \n " + e.getMessage(), "Error", 0);
        }
        finally{
            if(error == 13){
                Main.salir(this);
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void bAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAccederActionPerformed
        try
        {
            if (tfUsuario.getText().isEmpty())
            {
                throw new Excepcion(1);
            }
            else if (String.copyValueOf(pfContrasenna.getPassword()).isEmpty())
            {
                throw new Excepcion(2);
            }
            else{

                Main.accederPrincipal(tfUsuario.getText(), pfContrasenna.getPassword(), Integer.parseInt(jTextField1.getText()) );
            }
        }
        catch (Excepcion e)
        {
            pfContrasenna.setText("");
            pfContrasenna.grabFocus();
            JOptionPane.showMessageDialog(this, e.getMessage() + "(" + cont + "/3)", "Error", 0);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getClass() + " \n " + e.getMessage(), "Error", 0);
        }
        finally{
            if(error == 13){
                Main.salir(this);
            }
        }
    }//GEN-LAST:event_bAccederActionPerformed

    private void tfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAcceder;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel imgfondo;
    private javax.swing.JLabel imgpassw;
    private javax.swing.JLabel imgusu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logotipo;
    private javax.swing.JPasswordField pfContrasenna;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
