/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controladora.Main;
import Excepciones.*;
import UML.Equipo;
import UML.Jugador;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Vista para la modificacion de equipos.
 * Fecha de creación de la vista: 24/04/2018
 * @author eqdaw04
 */
public class VModificarEquipo extends javax.swing.JDialog {

    /**
     * Creates new form VModificarEquipo2
     */
    private static Equipo e;
    //array de jugadores integrantes del equipo
    private static ArrayList<Jugador> jEquipo;
    //array de jugadores disponibles
    private static ArrayList<Jugador> jDisp;
    
    public VModificarEquipo(String usu) throws Exception {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        ImageIcon fondo = new ImageIcon("../../imagenes/fondo2.jpg");
        Icon icono = new ImageIcon (fondo.getImage().getScaledInstance(imgfondo.getWidth(), imgfondo.getHeight(), Image.SCALE_DEFAULT));
        imgfondo.setIcon(icono);
        this.repaint();
        
        e = Main.ConsultarEquipoPorUsuario(usu);
        if(e != null){
            nombeEquipo.setText(e.getNombre());
            rellenar();
        }
        else{
            throw new Excepcion(33);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombeEquipo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liJugEqui = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        liJugDisp = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        bEliminar = new javax.swing.JButton();
        bAnnadir = new javax.swing.JButton();
        bConsultar = new javax.swing.JButton();
        tfSueldo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bSalir = new javax.swing.JButton();
        imgfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(931, 675));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 30)); // NOI18N
        jLabel1.setText("Modificar Equipo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(236, 27, 223, 39);

        nombeEquipo.setFont(new java.awt.Font("Bauhaus 93", 0, 30)); // NOI18N
        nombeEquipo.setForeground(new java.awt.Color(51, 102, 255));
        nombeEquipo.setText("NOMBREEQUIPO");
        getContentPane().add(nombeEquipo);
        nombeEquipo.setBounds(483, 27, 247, 39);

        liJugEqui.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        liJugEqui.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        liJugEqui.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                liJugEquiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(liJugEqui);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 185, 280, 214);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel2.setText("Jugadores en el equipo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 147, 209, 21);

        liJugDisp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        liJugDisp.setToolTipText("");
        liJugDisp.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                liJugDispValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(liJugDisp);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(520, 185, 270, 214);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel3.setText("Sueldo del jugador:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(241, 437, 170, 21);

        bEliminar.setText("Eliminar Jugador");
        bEliminar.setEnabled(false);
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bEliminar);
        bEliminar.setBounds(70, 466, 150, 25);

        bAnnadir.setText("Añadir Jugador");
        bAnnadir.setEnabled(false);
        bAnnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnadirActionPerformed(evt);
            }
        });
        getContentPane().add(bAnnadir);
        bAnnadir.setBounds(640, 480, 150, 25);

        bConsultar.setText("Consultar");
        bConsultar.setEnabled(false);
        bConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(bConsultar);
        bConsultar.setBounds(368, 280, 110, 25);

        tfSueldo.setEditable(false);
        tfSueldo.setText("Sueldo");
        getContentPane().add(tfSueldo);
        tfSueldo.setBounds(416, 434, 110, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel4.setText("Jugadores Disponibles:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 151, 201, 21);

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bSalir);
        bSalir.setBounds(717, 523, 73, 25);
        getContentPane().add(imgfondo);
        imgfondo.setBounds(0, 0, 860, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void liJugEquiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_liJugEquiValueChanged
        bEliminar.setEnabled(true);
        bConsultar.setEnabled(true);
        bAnnadir.setEnabled(false);
        liJugDisp.clearSelection();
        tfSueldo.setText(String.valueOf(jEquipo.get(liJugEqui.getSelectedIndex()).getSueldo()));
    }//GEN-LAST:event_liJugEquiValueChanged

    private void liJugDispValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_liJugDispValueChanged
        bEliminar.setEnabled(false);
        bConsultar.setEnabled(true);
        bAnnadir.setEnabled(true);
        liJugEqui.clearSelection();
        tfSueldo.setText(String.valueOf(jDisp.get(liJugDisp.getSelectedIndex()).getSueldo()));
    }//GEN-LAST:event_liJugDispValueChanged

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        try{
            if(Main.EliminarJugadorEquipo(liJugEqui.getSelectedValue())){
                JOptionPane.showMessageDialog(this, "Jugador eliminado exitosamente");
                rellenar();
                bEliminar.setEnabled(false);
            }else{
                throw new Excepcion(32);
            }
        }
        catch(Excepcion ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", 0);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, e.getClass() + " \n " + ex.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bAnnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnadirActionPerformed
        try{
            if(Main.AnnadirJugadorEquipo(liJugDisp.getSelectedValue(),String.valueOf(e.getIdEquipo()))){
                JOptionPane.showMessageDialog(this, "Jugador añadido exitosamente");
                rellenar();
                bAnnadir.setEnabled(false);
            }
        }  catch (SQLException ex){
            switch(ex.getErrorCode()){
                case 20001:
                JOptionPane.showMessageDialog(this, new Excepcion(28).getMessage());
                break;
                case 20002:
                JOptionPane.showMessageDialog(this, new Excepcion(29).getMessage());
                break;
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, e.getClass() + " \n " + ex.getMessage(), "Error", 0);
        }
        
    }//GEN-LAST:event_bAnnadirActionPerformed

    private void bConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarActionPerformed
        try{
            if(liJugEqui.isSelectionEmpty()){
                liJugEqui.clearSelection();
                Main.abrirVJugador(Main.consultarJugadorNickname(liJugDisp.getSelectedValue()));

            }else{
                liJugDisp.clearSelection();
                Main.abrirVJugador(Main.consultarJugadorNickname(liJugEqui.getSelectedValue()));  
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, e.getClass() + " \n " + ex.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_bConsultarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        Main.cerrar(this);

    }//GEN-LAST:event_bSalirActionPerformed

    private void rellenar() throws Exception{
        //No entiendo muy bien porque, pero sipongo directamente el codigo el segundo modelo (sea cual sea) no funciona correctamente
        rellenar1();
        rellenar2();    
    }
    
    /**
     * Metodo para buscar los jugadores que forman el equipo y rellenar una lista con ellos. 
     */
    private void rellenar1() throws Exception{
        jEquipo=new ArrayList();
        jEquipo=Main.obtenerJugEqui(String.valueOf(e.getIdEquipo()));
        DefaultListModel<String> model = new DefaultListModel();
        for (int x=0;x < jEquipo.size();x++){
            model.addElement(jEquipo.get(x).getNickname());
        }
        liJugEqui.setModel(model);
    }
    
    /**
     * Metodo para buscar jugadores sin equipo y rellenar una lista con ellos.
     */
    
    private void rellenar2() throws Exception{
        jDisp=new ArrayList();
        jDisp=Main.consultarJugadoresDisponibles();
        DefaultListModel<String> modelo = new DefaultListModel();
        for (int y=0;y< jDisp.size();y++){
            modelo.addElement(jDisp.get(y).getNickname());
        }
        liJugDisp.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnnadir;
    private javax.swing.JButton bConsultar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel imgfondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> liJugDisp;
    private javax.swing.JList<String> liJugEqui;
    private javax.swing.JLabel nombeEquipo;
    private javax.swing.JTextField tfSueldo;
    // End of variables declaration//GEN-END:variables
}
